import type { Metadata } from "next";
import Script from 'next/Script';
import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from "next/font/google";
import "./globals.css";

import 'boxicons/css/boxicons.css'
import ImportBsJS from "@/components/ImportBsJS";
import { SideBar, NavBar} from "@/components";

const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   deScription: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SideBar/>
      <section id="content">
      <NavBar/>
        {children}
      </section>
     </body>
    </html>
  );
}
