import type { Metadata } from "next";
import Script from 'next/Script';
import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/contexts/authContext'; 
import 'boxicons/css/boxicons.css'
import ImportBsJS from "@/components/ImportBsJS";
import { SideBar, NavBar} from "@/components";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/autoplay';

const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   deScription: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body className={inter.className}>
        {children}
     </body>
    </html>
    </AuthProvider>
  );
}
