export const car = [
    {
    id : '2323DSSX23',
    name : 'Mercedes Grand Sedan',
    category: 'A',
    brand: 'Chevolet',
    insuranceFile: null,
    registrationCardFile: null,
    fuelType: 'Petrol',
    hasAC: true,
    childSeat: false,
    gps: false,
    luggage: true,
    music: false,
    seatBelt: false,
    sleepingBed: false,
    water: false,
    bluetooth: false,
    onboardComputer: false,
    audioInput: false,
    longTermTrips: true,
    carKit: false,
    remoteCentralLocking: false,
    climateControl: false,
    mileage: '40,000',
    transmission: 'Manual',
    seats: '5 Adults',
    luggageCapacity: '4 Bags',
    fuel: 'Petrol',
    description: '',
    photos: [],}
]